ROOT_PATH='../'

SRC_DIR='src/'
DATA_DIR='data/'
MODEL_DIR='model/'
INPUT_DATA_DIR='data/raw'
OUTPUT_DATA_DIR='data/processed'

INDEX_FILE='Data_Entry_2017.csv'
TRAIN_VAL_FILE='train_val_list.txt'
TEST_VAL_FILE='test_list.txt'

SEED=1

TEST_SIZE=0.2

NUM_EPOCHS=10
TRAIN_BATCH_SIZE=2048
VAL_BATCH_SIZE=64
TEST_BATCH_SIZE=32

TRAIN_WORKERS=4
VAL_WORKERS=4
TEST_WORKERS=2

LEARNING_RATE=0.01